version: '3.1'

services:
  db-dev:
    image: postgres:11
 #   environment:
 #     POSTGRES_PASSWORD: example
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
